{
 "title": "Vault Consul Dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Vault Seal Status",
   "type": "table",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "count(consul_health_checks_passing{check_name=\"Vault Sealed Status\",job=\"vault-server\",status=\"passing\"}) by (node,check_id,status)",
     "legendFormat": "he"
    },
    {
     "expr": "count(consul_health_checks_passing{check_name=\"Vault Sealed Status\",job=\"vault-server\",status=\"critical\"}) by (node,check_id,status)"
    }
   ]
  },
  {
   "title": "Consul Server Count",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(consul_rpc_request_value{role=\"consul-server\"})"
    }
   ]
  },
  {
   "title": "Consul Raft Leader LastContact",
   "type": "gauge",
   "description": "Measures the time since the leader was last able to contact the follower nodes when checking its leader lease",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "consul_raft_leader_lastContact_upper"
    }
   ]
  },
  {
   "title": "CPU Utilisation",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Utilisation",
     "type": "text",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 1 },
     "content": "# CPU Utilisation\n\nEncryption can place a heavy demand on CPU. If the CPU is too busy, Vault may have trouble keeping up with the incoming request load. You may also want to monitor each CPU individually to make sure requests are evenly balanced across all CPUs.\n\nConsul is not particularly demanding of CPU time, but a spike in CPU usage might indicate too many operations taking place at once, and iowait_cpu is critical -- it means Consul is waiting for data to be written to disk, a sign that Raft might be writing snapshots to disk too often.\n"
    },
    {
     "title": "Consul User CPU Usage",
     "type": "graph",
     "description": "Percentage of CPU being used by user processes on Consul servers (processes including Consul)",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 5 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "cpu_usage_user{cpu=\"cpu-total\",job=\"consul-1-server\"}",
       "legendFormat": "cpu-usage-consul-1-server"
      },
      {
       "expr": "cpu_usage_user{cpu=\"cpu-total\",job=\"consul-2-server\"}",
       "legendFormat": "cpu-usage-consul-2-server"
      },
      {
       "expr": "cpu_usage_user{cpu=\"cpu-total\",job=\"consul-3-server\"}",
       "legendFormat": "cpu-usage-consul-3-server"
      }
     ]
    },
    {
     "title": "Consul CPU IOWait",
     "type": "graph",
     "description": "Percentage of CPU time spent waiting for I/O tasks to complete. Look for iowait greater than 10%",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 5 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "cpu_usage_iowait{cpu=\"cpu-total\",job=\"consul-1-server\"}",
       "legendFormat": "cpu-usage-consul-1-server"
      },
      {
       "expr": "cpu_usage_iowait{cpu=\"cpu-total\",job=\"consul-2-server\"}",
       "legendFormat": "cpu-usage-consul-2-server"
      },
      {
       "expr": "cpu_usage_iowait{cpu=\"cpu-total\",job=\"consul-3-server\"}",
       "legendFormat": "cpu-usage-consul-3-server"
      }
     ]
    },
    {
     "title": "Vault User CPU Usage",
     "type": "graph",
     "description": "Percentage of CPU being used by user processes on Vault server (processes including Vault)",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 5 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "cpu_usage_user{cpu=\"cpu-total\",job=\"vault-server\"}",
       "legendFormat": "cpu-usage-vault-server"
      }
     ]
    },
    {
     "title": "Vault CPU IOWait",
     "type": "graph",
     "description": "Percentage of CPU time spent waiting for I/O tasks to complete. Look for iowait greater than 10%",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 5 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "cpu_usage_iowait{cpu=\"cpu-total\",job=\"vault-server\"}",
       "legendFormat": "cpu-usage-vault-1-server"
      }
     ]
    }
   ]
  },
  { "title": "Memory Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Memory Usage",
   "type": "text",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 6 },
   "content": "# Memory Usage\n\n## Consul\nConsul keeps all of its data in memory. If Consul consumes all available memory, it will crash. You should also monitor\ntotal available RAM to make sure some RAM is available for other processes, and swap usage should remain at 0% for best performance.\n\n## Vault\nVault doesn't need as much memory as Consul, but if it does run out, it too will crash. You should also monitor total\navailable RAM to make sure some RAM is available for other processes, and swap usage should remain at 0% for best performance\n\n### What to look for\nIf sys_bytes exceeds 90% of total_bytes, if mem.used_percent is over 90%, or if swap.used_percent is greater\nthan 0."
  },
  {
   "title": "Consul memory used percent",
   "type": "graph",
   "description": "Percentage of physical memory in use",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mem_used_percent{job=\"consul-1-server\"}",
     "legendFormat": "mem-used-percent-consul-1-server"
    },
    {
     "expr": "mem_used_percent{job=\"consul-2-server\"}",
     "legendFormat": "mem-used-percent-consul-2-server"
    },
    {
     "expr": "mem_used_percent{job=\"consul-3-server\"}",
     "legendFormat": "mem-used-percent-consul-3-server"
    }
   ]
  },
  {
   "title": "Consul memory used percent delta",
   "type": "graph",
   "description": "Delta of Percentage of physical memory in use",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "delta(mem_used_percent{job=\"consul-1-server\"}[5m])",
     "legendFormat": "delta-consul-1-server"
    },
    {
     "expr": "delta(mem_used_percent{job=\"consul-2-server\"}[5m])",
     "legendFormat": "delta-consul-2-server"
    },
    {
     "expr": "delta(mem_used_percent{job=\"consul-3-server\"}[5m])",
     "legendFormat": "delta-consul-3-server"
    }
   ]
  },
  {
   "title": "Vault memory used percent",
   "type": "graph",
   "description": "Percentage of physical memory in use",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mem_used_percent{job=\"vault-server\"}",
     "legendFormat": "mem-used-percent-vault-server"
    }
   ]
  },
  {
   "title": "Vault memory used percent delta",
   "type": "graph",
   "description": "Delta of Percentage of physical memory in use",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "delta(mem_used_percent{job=\"vault-server\"}[5m])",
     "legendFormat": "delta-vault-server"
    }
   ]
  },
  {
   "title": "Network Utilisation",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "panels": [
    {
     "title": "Network Utilisation",
     "type": "text",
     "gridPos": { "h": 6, "w": 7, "x": 0, "y": 13 },
     "content": "# Network Utilisation\n\nA sudden spike in network traffic to Vault might be the result of a misconfigured client causing too many requests, or additional load you didn't plan for. \n\nLook for sudden large changes to the net metrics (greater than 50% deviation from baseline)."
    },
    {
     "title": "Vault Network Traffic Sent",
     "type": "graph",
     "description": "Bits/second sent on each network interface",
     "gridPos": { "h": 6, "w": 5, "x": 7, "y": 13 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(net_bytes_sent{job=\"vault-server\"}[1m])*8",
       "legendFormat": "network-bits-sent-vault-1-server"
      }
     ]
    },
    {
     "title": "Vault Network Received (bits/second)",
     "type": "graph",
     "description": "Network traffic received on each network interface (bits/second)",
     "gridPos": { "h": 6, "w": 4, "x": 12, "y": 13 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(net_bytes_recv{job=\"vault-server\"}[1m])*8",
       "legendFormat": "network-bits-received-vault-1-server"
      }
     ]
    },
    {
     "title": "Consul Network Sent (bits/second)",
     "type": "graph",
     "description": "Network traffic sent from each network interface (bits/second)",
     "gridPos": { "h": 6, "w": 4, "x": 16, "y": 13 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(net_bytes_sent{job=\"consul-1-server\"}[1m])*8",
       "legendFormat": "network-bits-sent-consul-1-server"
      },
      {
       "expr": "rate(net_bytes_sent{job=\"consul-2-server\"}[1m])*8",
       "legendFormat": "network-bits-sent-consul-2-server"
      },
      {
       "expr": "rate(net_bytes_sent{job=\"consul-3-server\"}[1m])*8",
       "legendFormat": "network-bits-sent-consul-3-server"
      }
     ]
    },
    {
     "title": "Consul Network Received (bits/second)",
     "type": "graph",
     "description": "Network traffic received on each network interface (bits/second)",
     "gridPos": { "h": 6, "w": 4, "x": 20, "y": 13 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(net_bytes_recv{job=\"consul-1-server\"}[1m])*8",
       "legendFormat": "network-bits-received-consul-1-server"
      },
      {
       "expr": "rate(net_bytes_recv{job=\"consul-2-server\"}[1m])*8",
       "legendFormat": "network-bits-received-consul-2-server"
      },
      {
       "expr": "rate(net_bytes_recv{job=\"consul-3-server\"}[1m])*8",
       "legendFormat": "network-bits-received-consul-3-server"
      }
     ]
    }
   ]
  },
  {
   "title": "File Descriptor Usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "File Descriptor Usage",
     "type": "text",
     "gridPos": { "h": 6, "w": 7, "x": 0, "y": 14 },
     "content": "# File Descriptor Usage\n\nHeavy utilisation of the network due to lots of connections can often cause high utilisation of file-descriptors. There are 2 metrics that should be monitored.\n\nIf the file-nr reaches 80% of the file-max then you should alert and investigate"
    },
    {
     "title": "Vault File Descriptor Usage Percentage",
     "type": "graph",
     "description": "Number of file handles being used across all processes on host as a percentage of total number of available file handles",
     "gridPos": { "h": 6, "w": 8, "x": 7, "y": 14 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "linux_sysctl_fs_file_nr{job=\"vault-server\"}/linux_sysctl_fs_file_max{job=\"vault-server\"} * 100",
       "legendFormat": "file-descriptor-used-percent-vault-server"
      }
     ]
    },
    {
     "title": "Consul File Descriptor Usage Percentage",
     "type": "graph",
     "description": "Number of file handles being used across all processes on host as a percentage of total number of available file handles",
     "gridPos": { "h": 6, "w": 9, "x": 15, "y": 14 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "linux_sysctl_fs_file_nr{job=\"consul-1-server\"}/linux_sysctl_fs_file_max{job=\"consul-1-server\"} * 100",
       "legendFormat": "file-descriptor-used-percent-consul-1-server"
      },
      {
       "expr": "linux_sysctl_fs_file_nr{job=\"consul-2-server\"}/linux_sysctl_fs_file_max{job=\"consul-2-server\"} * 100",
       "legendFormat": "file-descriptor-used-percent-consul-2-server"
      },
      {
       "expr": "linux_sysctl_fs_file_nr{job=\"consul-3-server\"}/linux_sysctl_fs_file_max{job=\"consul-3-server\"} * 100",
       "legendFormat": "file-descriptor-used-percent-consul-3-server"
      }
     ]
    }
   ]
  },
  {
   "title": "Slow Consul Response Time - Vault",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "Slow Consul Response Time - Vault",
     "type": "text",
     "gridPos": { "h": 7, "w": 5, "x": 0, "y": 5 },
     "content": "# Slow Consul Response Time - Vault\nThese metrics indicate how long it takes for Consul to handle requests from Vault\n"
    },
    {
     "title": "Upper Value of Operations against Raft Storage Backend",
     "type": "graph",
     "gridPos": { "h": 7, "w": 19, "x": 5, "y": 5 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "delta(vault_raft_apply_value{job=\"vault-server\"}[5m])",
       "legendFormat": "get-upper-vault-server"
      }
     ]
    }
   ]
  },
  {
   "title": "Vault WAL Processing",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "Vault WAL Processing",
     "type": "text",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 6 },
     "content": "# Vault Write Ahead Logs Processing\n\nThe Vault write-ahead logs (WALs) are used to replicate Vault between clusters. Surprisingly, the WAL's are kept even if replication is not currently enabled. The WAL is purged every few seconds by a garbage collector. But if Vault is under heavy load, the WAL may start to grow, putting pressure on Consul.\n\n* vault_wal_persist: WALs Amount of time required to persist the Vault write-ahead logs (WAL) to the Consul backend.\n* vault_wal_flushReady: Amount of time required to flush the Vault write-ahead logs (WAL) to the persist queue\n\nLook for flushReady over 500ms, or vault.wal.persist is over 1000ms."
    },
    {
     "title": "Vault WAL FlushReady",
     "type": "graph",
     "description": "Amount of time required to flush the Vault write-ahead logs (WAL) to the persist queue",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 6 },
     "yaxes": [
      { "format": "short", "label": "ms" }
     ],
     "targets": [
      {
       "expr": "vault_wal_flushReady_upper{job=\"vault-server\"}",
       "legendFormat": "vault-wal-flushReady-upper-vault-server"
      }
     ]
    },
    {
     "title": "Vault WAL Persist",
     "type": "graph",
     "description": "WALs Amount of time required to persist the Vault write-ahead logs (WAL) to the Consul backend",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 6 },
     "yaxes": [
      { "format": "short", "label": "ms" }
     ],
     "targets": [
      {
       "expr": "vault_wal_persistWALs_upper{job=\"vault-server\"}",
       "legendFormat": "vault-wal-persistWals-upper-vault-server"
      }
     ]
    }
   ]
  },
  { "title": "Consul Leadership Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "Consul Raft State Leader",
   "type": "graph",
   "description": "Increments whenever a Consul server becomes a leader",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "consul_raft_state_leader{job=\"consul-1-server\"}",
     "legendFormat": "consul-1-server"
    },
    {
     "expr": "consul_raft_state_leader{job=\"consul-2-server\"}",
     "legendFormat": "consul-2-server"
    },
    {
     "expr": "consul_raft_state_leader{job=\"consul-3-server\"}",
     "legendFormat": "consul-3-server"
    }
   ]
  },
  {
   "title": "Consul Raft State Candidate",
   "type": "graph",
   "description": "Increments whenever a Consul server starts an election",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "consul_raft_state_candidate{job=\"consul-1-server\"}\n",
     "legendFormat": "candidate-consul-1-server"
    },
    {
     "expr": "consul_raft_state_candidate{job=\"consul-2-server\"}\n",
     "legendFormat": "candidate-consul-2-server"
    },
    {
     "expr": "consul_raft_state_candidate{job=\"consul-3-server\"}\n",
     "legendFormat": "candidate-consul-3-server"
    }
   ]
  },
  {
   "title": "Consul Cluster Health",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "collapsed": true,
   "panels": [
    {
     "title": "Consul Autopilot Healthy",
     "type": "graph",
     "description": "Tracks the overall health of the server cluster. If all servers considered healthy by Autopilot, this will be set to 1. If any are unhealthy, this will be 0.",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 8 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "consul_autopilot_healthy_value{job=\"consul-1-server\"}",
       "legendFormat": "consul-autopilot-healthy-consul-1-server"
      },
      {
       "expr": "consul_autopilot_healthy_value{job=\"consul-2-server\"}",
       "legendFormat": "consul-autopilot-healthy-consul-2-server"
      },
      {
       "expr": "consul_autopilot_healthy_value{job=\"consul-3-server\"}",
       "legendFormat": "consul-autopilot-healthy-consul-3-server"
      }
     ]
    }
   ]
  },
  { "title": "Consul Garbage Collection", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "Consul Garbage Collection",
   "type": "text",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 29 },
   "content": "\n# Consul Gabarge Collection\n\nGC pause is a \"stop-the-world\" event, meaning that all runtime threads are blocked until GC completes. Normally these pauses last only a few nanoseconds. But if memory usage is high, the Go runtime may GC so frequently that it starts to slow down Consul.\n\n\n\n"
  },
  {
   "title": "Consul Garbage Collection",
   "type": "graph",
   "description": "Number of nanoseconds consumed by stop-the-world garbage collection (GC) pauses since Consul started",
   "gridPos": { "h": 6, "w": 16, "x": 7, "y": 29 },
   "yaxes": [
    { "format": "short", "label": "seconds" }
   ],
   "targets": [
    {
     "expr": "rate(consul_runtime_total_gc_pause_ns_value{job=\"consul-1-server\"}[1m])/1000000000",
     "legendFormat": "consul-runtime-total-gc-pause-ns-consul-1-server"
    },
    {
     "expr": "rate(consul_runtime_total_gc_pause_ns_value{job=\"consul-2-server\"}[1m])/1000000000",
     "legendFormat": "consul-runtime-total-gc-pause-ns-consul-2-server"
    },
    {
     "expr": "rate(consul_runtime_total_gc_pause_ns_value{job=\"consul-3-server\"}[1m])/1000000000",
     "legendFormat": "consul-runtime-total-gc-pause-ns-consul-3-server"
    }
   ]
  }
 ]
}